### ISSUE TITLE
Complete minisat compile

### ISSUE THREAD

**Issue by vpeter4** [CvH/oe-addon-minisatip#1]
From unofficial addon repository copy packages libdvbcsa and dvb-apps (or just whole repository in packages folder).
Patch is not required.

minisat package.mk:

```javascript
PKG_DEPENDS_TARGET="toolchain dvb-apps libdvbcsa"

make_target() {
    DVB_APPS_DIR=$(get_build_dir dvb-apps)
		
    make CC=$TARGET_CC \
    CFLAGS="$CFLAGS -I$DVB_APPS_DIR/lib" \
    LDFLAGS="$LDFLAGS $DVB_APPS_DIR/lib/libdvben50221/libdvben50221.a \
             $DVB_APPS_DIR/lib/libucsi/libucsi.a \
             $DVB_APPS_DIR/lib/libdvbapi/libdvbapi.a \
             $SYSROOT_PREFIX/usr/lib/libdvbcsa.a -lpthread" \
    DVBCSA=yes \
    DVBCA=yes
}
```

**Comment by CvH** [comment]
ah great :+1: 
(I merge it as soon I got a bit time !)

tx

**Comment by CvH** [comment]
@vpeter4 
any clue why it fails at WetekPlay ?
http://hastebin.com/pejozatafa.pas
x64, RPi1/2 work

**Comment by vpeter4** [comment]
Use this make_target() in dvb-apps package.mk
```javascript
make_target() {
	sed -i "s|cat /usr|cat $SYSROOT_PREFIX/usr|g" util/av7110_loadkeys/generate-keynames.sh

  make -C lib VERSION_FILE=$SYSROOT_PREFIX/usr/include/linux/dvb/version.h
  make -C util VERSION_FILE=$SYSROOT_PREFIX/usr/include/linux/dvb/version.h
}
```

**Comment by CvH** [comment]
Any clue why it ***only*** fails at wetek ? This looks like it had to fail at all platforms?!

**Comment by vpeter4** [comment]
generate-keynames.sh script tooks file from host Linux kernel. And seems some symbols are missing In Wetek kernel.
My change gets everything from kernel used in project.

**Comment by CvH** [comment]
grumpy cat didn't "maintain" it anymore? (

**Comment by vpeter4** [comment]
No comment - don't want to part in conflicts anymore.

**Comment by CvH** [comment]
ah ok, I read something - somewhere but this kind of gossip I read for years and I really don't take it seriously ;)
